# Google Cloud Build configuration para AgroAssist IA
# Configuración para build automático desde GitHub con variables Vite

steps:
# Step 1: Build de la imagen Docker con variables de entorno Vite
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/agroassist-ia:$COMMIT_SHA'
    - '-t'
    - 'gcr.io/$PROJECT_ID/agroassist-ia:latest'
    - '--build-arg'
    - 'VITE_TAVUS_API_KEY=${_VITE_TAVUS_API_KEY}'
    - '--build-arg'
    - 'VITE_REPLICA_ID=${_VITE_REPLICA_ID}'
    - '--build-arg'
    - 'VITE_PERSONA_ID=${_VITE_PERSONA_ID}'
    - '.'
  timeout: '1200s'

# Step 2: Push imagen a Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '--all-tags', 'gcr.io/$PROJECT_ID/agroassist-ia']

# Step 3: Deploy a Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'agroassist-ia'  # Nombre del servicio
    - '--image'
    - 'gcr.io/$PROJECT_ID/agroassist-ia:$COMMIT_SHA'
    - '--region'
    - 'us-central1'  # Ajustar según tu región preferida
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--memory'
    - '512Mi'
    - '--cpu'
    - '1'
    - '--min-instances'
    - '0'
    - '--max-instances'
    - '10'
    - '--set-env-vars'
    - 'NODE_ENV=production'

# Variables de sustitución (REEMPLAZAR CON TUS VALORES REALES)
substitutions:
  _VITE_TAVUS_API_KEY: 'd258143c5f594287bd9b50cc14fe48ad'
  _VITE_REPLICA_ID: 'rf4703150052'
  _VITE_PERSONA_ID: 'p0d190fec528'

# Configuración de recursos y logging
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  
timeout: '1200s'

# Imágenes generadas
images:
  - 'gcr.io/$PROJECT_ID/agroassist-ia:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/agroassist-ia:latest'
